Connect movies from server
htmlacademy-react/1452537-what-to-watch-7 pull request #11
Opened 2021-07-12 19:22 UTC by Nikulichka

2021-07-13 17:55 UTC, Dima-Dim requested changes

2021-07-13 17:55 UTC, Dima-Dim commented on project/src/index.js
> +store.dispatch(checkAuth());
Нам точно это всё нужно получить именно здесь? Кажется что на этом уровне нам ещё не нужны все эти данные.

2021-07-13 17:55 UTC, Dima-Dim commented on project/src/store/action.js
> +  filterListMovies: (genre, movies, originalMovies) => ({
В глобальном сторе не нужно хранить копию отфильтрованных или отсортированных данных. Можно сохранить тип фильтра или сортировки, но само действие нужно производить по месту, где оно нужно.

2021-07-13 20:17 UTC, Nikulichka commented on project/src/index.js
> +store.dispatch(checkAuth());
Просто не успела доделать вчера. Сегодня доделала)

2021-07-18 08:38 UTC, Dima-Dim commented on project/src/components/catalog-like-this/catalog-like-this.jsx
>              <article className="small-film-card catalog__films-card"
`article` можно было бы вынести в отдельный компонент.

2021-07-18 08:38 UTC, Dima-Dim commented on project/src/store/middlewares/redirect.js
> +export const redirect = (_store) => (next) => (action) => {
https://reactrouter.com/web/api/Redirect не подойдёт?

2021-07-18 08:38 UTC, Dima-Dim commented on project/src/store/reducer.js
> +    case ActionType.FILTER_LIST_MOVIES:
Я ещё не говорил тебе что держать в стейте дублирующие данные не хорошо? :)

2021-07-18 08:38 UTC, merged

2021-07-18 18:12 UTC, Nikulichka commented on project/src/store/reducer.js
> +    case ActionType.FILTER_LIST_MOVIES:
Имеется ввиду, movies и originalMovies? movies мне нужен чтобы изменять фильтрацией, originalMovies неизменяемый..

2021-07-19 03:03 UTC, Dima-Dim commented on project/src/store/reducer.js
> +    case ActionType.FILTER_LIST_MOVIES:
Ты можешь хранить параметры фильтрации, но не уже отфильтрованные данные, потому что иначе получается дублирование.