Обратная сторона реальности
htmlacademy-react/1452537-what-to-watch-7 pull request #5
Opened 2021-06-22 19:30 UTC by Nikulichka

---
:mortar_board: [Обратная сторона реальности](https://up.htmlacademy.ru/react/7/user/1452537/tasks/5)

2021-06-24 11:26 UTC, Dima-Dim requested changes

2021-06-24 11:26 UTC, Dima-Dim commented on project/src/components/add-review-screen/add-review-screen.jsx
> +      [name]: value,
Какая-то не очевидная штука.
У нас в стейте ещё, вроде как, должны быть поля `reviewText` и `rating`?

2021-06-24 11:26 UTC, Dima-Dim commented on project/src/components/add-review-screen/add-review-screen.jsx
> +              onChange={(event) => handleInputChange(event)}
Вынести функцию в переменную.

2021-06-24 11:26 UTC, Dima-Dim commented on project/src/components/film-card-buttons/film-card-buttons.jsx
> +        onClick={() => history.push(AppRoute.PLAYER)}
Все такие функции вынести в переменные для оптимизации работы приложения.

2021-06-24 11:26 UTC, Dima-Dim commented on project/src/components/film-card-nav/film-card-nav.jsx
> +    setState({ activeItem: { [activeState]: true } });
Вообще же не читается такое.

2021-06-24 14:44 UTC, Nikulichka commented on project/src/components/film-card-buttons/film-card-buttons.jsx
> +        onClick={() => history.push(AppRoute.PLAYER)}
Это вот так: 
const onPlayClick = () => history.push(AppRoute.PLAYER); 
onClick={onPlayClick} ?

2021-06-24 15:09 UTC, Nikulichka commented on project/src/components/film-card-nav/film-card-nav.jsx
> +    setState({ activeItem: { [activeState]: true } });
Я не понимаю как по другому установить "Overview" активным при загрузке.

2021-06-25 04:27 UTC, Dima-Dim commented on project/src/components/film-card-buttons/film-card-buttons.jsx
> +        onClick={() => history.push(AppRoute.PLAYER)}
Ага, только https://up.htmlacademy.ru/react/7/criteries#d2

2021-06-25 04:27 UTC, Dima-Dim commented on project/src/components/film-card-nav/film-card-nav.jsx
> +    setState({ activeItem: { [activeState]: true } });
Дело не в том что написано :) а как оно написано. Когда оно вот так в одну строчку, нужно прям вдумываться что здесь происходит.

2021-06-26 17:53 UTC, Dima-Dim commented on project/src/components/add-review-screen/add-review-screen.jsx
> +              onChange={(event) => setState({...state, reviewText: event.target.value})}
Функцию сюда нужно передавать переменной, а создавать его до return-а.

2021-06-26 17:53 UTC, Dima-Dim commented on project/src/components/rating/rating.jsx
> +            onClick={(event) => setState({...state, rating: event.target.defaultValue})}
Тоже выносим функцию в переменную.

2021-06-26 17:53 UTC, merged